development:
  adapter: postgresql
  encoding: unicode
  database: campuscoupons_development
  username: campuscoupons
  password: l8Uv4kSHh4

test:
  adapter: postgresql
  encoding: unicode
  database: campuscoupons_test
  username: campuscoupons
  password: l8Uv4kSHh4

production:
  adapter: postgresql
  encoding: unicode
  database: campuscoupons_production
  username: campuscoupons
  password: l8Uv4kSHh4

cucumber:
  <<: *test